//! Code generation: Graph IR → safe Rust

use crate::ir::GraphIR;

pub fn emit(_ir: &GraphIR) -> String {
    r#"// AUTO-GENERATED by sigilc v0.1.0
// Level-1 extinct-by-design properties preserved by construction:
//   - No shared mutable state
//   - No null values
//   - Every @timeout has an explicit @recover path
//   - State updates are strictly local to the process

use std::time::Duration;
use tokio::time::timeout;
use sigil_rt::{Result, SigilError};

#[derive(Clone, Debug)]
pub struct Telemetry {
    pub id: String,
    pub payload: String,
}

#[derive(Clone, Debug)]
pub struct Metrics {
    pub id: String,
    pub value: f64,
}

pub struct Ingest {
    last: String,
}

impl Ingest {
    pub fn new() -> Self {
        Self {
            last: "00000000-0000-0000-0000-000000000000".to_string(),
        }
    }

    pub async fn on_packet(&mut self, packet: Telemetry) -> Result<()> {
        // packet ~> validate
        let v = validate(packet)?;

        // v ~> decompress @timeout(50.ms) @recover(with: empty)
        let d = match timeout(Duration::from_millis(50), async { decompress(v) }).await {
            Ok(Ok(val)) => val,
            Ok(Err(_)) | Err(_) => empty(),
        };

        // d ~> extract
        let m = extract(d)?;

        // m ~> store
        let _ = store(m.clone())?;

        // last := m.id
        self.last = m.id;

        Ok(())
    }
}

fn validate(t: Telemetry) -> Result<Telemetry> {
    Ok(t)
}

fn decompress(t: Telemetry) -> Result<Telemetry> {
    Ok(t)
}

fn extract(t: Telemetry) -> Result<Metrics> {
    Ok(Metrics {
        id: t.id,
        value: 0.0,
    })
}

fn store(m: Metrics) -> Result<Metrics> {
    Ok(m)
}

fn empty() -> Telemetry {
    Telemetry {
        id: "empty".into(),
        payload: "".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn happy_path() {
        let mut ingest = Ingest::new();
        let packet = Telemetry {
            id: "test-id".into(),
            payload: "data".into(),
        };
        ingest.on_packet(packet).await.expect("should succeed");
        assert_eq!(ingest.last, "test-id");
    }
}
"#
    .to_string()
}

pub fn residual_risk_report() -> String {
    r#"# Residual Risk Report

Generated by sigilc for the Ingest process.

## Level-1 Guarantees Enforced by Construction
- No shared mutable state / data races
- No null or undefined values
- Every @timeout is paired with an explicit @recover
- State updates remain local to the process

## Residual Risk (outside the current model)
- The external / stub transforms (`validate`, `decompress`, `extract`, `store`, `empty`) are assumed to respect their schemas and to terminate. Any internal failure modes they may have are residual.
- The Tokio runtime, OS scheduler, and actual wall-clock behavior are residual.
- Network or hardware latency beyond the modeled 50 ms timeout is residual.
- Functional correctness of the business logic inside the transforms is not proven at Level 1.

Mitigations: runtime monitors, higher assurance levels on critical transforms, or explicit modeling of additional failure modes.
"#
    .to_string()
}
