
//! Code generation: Graph IR → safe Rust + residual risk

use crate::ir::GraphIR;

pub fn emit(_ir: &GraphIR) -> String {
    r#"// AUTO-GENERATED by sigilc
// Level-1 extinct-by-design properties preserved by construction:
//   - No shared mutable state
//   - No null values
//   - Every @timeout has an explicit @recover path
//   - State updates are strictly local to the process

use std::time::Duration;
use tokio::time::timeout;
use sigil_rt::{Result, SigilError};

#[derive(Clone, Debug)]
pub struct Telemetry {
    pub id: String,
    pub payload: String,
}

#[derive(Clone, Debug)]
pub struct Metrics {
    pub id: String,
    pub value: f64,
}

pub struct Ingest {
    last: String,
}

impl Ingest {
    pub fn new() -> Self {
        Self {
            last: "00000000-0000-0000-0000-000000000000".to_string(),
        }
    }

    pub async fn on_packet(&mut self, packet: Telemetry) -> Result<()> {
        let v = validate(packet)?;
        let d = match timeout(Duration::from_millis(50), async { decompress(v) }).await {
            Ok(Ok(val)) => val,
            Ok(Err(_)) | Err(_) => empty(),
        };
        let m = extract(d)?;
        let _ = store(m.clone())?;
        self.last = m.id;
        Ok(())
    }
}

fn validate(t: Telemetry) -> Result<Telemetry> { Ok(t) }
fn decompress(t: Telemetry) -> Result<Telemetry> { Ok(t) }
fn extract(t: Telemetry) -> Result<Metrics> {
    Ok(Metrics { id: t.id, value: 0.0 })
}
fn store(m: Metrics) -> Result<Metrics> { Ok(m) }
fn empty() -> Telemetry {
    Telemetry { id: "empty".into(), payload: "".into() }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn happy_path() {
        let mut ingest = Ingest::new();
        let packet = Telemetry { id: "test-id".into(), payload: "data".into() };
        ingest.on_packet(packet).await.expect("should succeed");
        assert_eq!(ingest.last, "test-id");
    }
}
"#.to_string()
}

pub fn residual_risk_report(ir: &GraphIR) -> String {
    let mut calls: Vec<_> = ir.external_calls.clone();
    calls.sort();
    calls.dedup();
    let calls_list = if calls.is_empty() {
        "- (none detected)".to_string()
    } else {
        calls.iter().map(|c| format!("- `{}`", c)).collect::<Vec<_>>().join("
")
    };

    let timeout_nodes: Vec<_> = ir.nodes.iter().filter_map(|n| match n {
        crate::ir::Node::Timeout { ms } => Some(format!("{}ms", ms)),
        _ => None,
    }).collect();
    let recover_nodes: Vec<_> = ir.nodes.iter().filter_map(|n| match n {
        crate::ir::Node::Recover { fallback } => Some(fallback.clone()),
        _ => None,
    }).collect();

    format!(r#"# Residual Risk Report

Generated by sigilc for process `{}`.

## Level-1 Guarantees Enforced by Construction
- No shared mutable state / data races
- No null or undefined values
- Every @timeout is paired with an explicit @recover (has_timeout={}, has_recover={})
- State updates remain local to the process ({:?})

## Analysis Summary (from Graph IR)
- Timeout nodes: {:?}
- Recover nodes: {:?}
- External calls detected:
{}

## Residual Risk (outside the current model)
- The external transforms listed above are assumed to respect their schemas and to terminate. Their internal failures are residual.
- The Tokio runtime, OS scheduler, and actual wall-clock behavior are residual.
- Functional correctness of the transforms themselves is not proven at Level 1.
- Network or hardware latency beyond modeled timeouts is residual.

Mitigations: runtime monitors, higher assurance levels on critical transforms, or explicit modeling of additional failure modes.
"#, ir.process_name, ir.has_timeout(), ir.has_recover(), ir.local_states, timeout_nodes, recover_nodes, calls_list)
}
