//! Backend: Program + Graph IR → ownership-safe Rust crate.
//! Level-1 guarantees are preserved by construction in the emitted code.

use crate::analysis::ir::GraphIR;
use crate::frontend::ast::{
    BinOp, Expr, Literal, OnHandler, Process, Program, Schema, Stmt, Tag, Type,
};
use std::collections::BTreeSet;

/// Emit a full Rust library source from the checked program and its Graph IR.
pub fn emit(program: &Program, ir: &GraphIR) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by sigilc — do not edit by hand\n");
    out.push_str("//\n");
    out.push_str(&format!("// Process: {}\n", ir.process_name));
    out.push_str(&format!(
        "// Local state: {}\n",
        if ir.local_states.is_empty() {
            "(none)".into()
        } else {
            ir.local_states.join(", ")
        }
    ));
    let timeouts: Vec<_> = ir
        .nodes
        .iter()
        .filter_map(|n| match n {
            crate::analysis::ir::Node::Timeout { ms, .. } => Some(format!("{ms}ms")),
            _ => None,
        })
        .collect();
    if !timeouts.is_empty() {
        out.push_str(&format!("// Timed stages: {}\n", timeouts.join(", ")));
    }
    out.push_str("//\n");
    out.push_str("// Level-1 guarantees preserved by construction:\n");
    out.push_str("//   - process-local state only (no shared mutability)\n");
    out.push_str("//   - no null values\n");
    out.push_str("//   - every @timeout has an explicit @recover path\n\n");

    out.push_str("use std::time::Duration;\n");
    out.push_str("use tokio::time::timeout;\n");
    out.push_str("use sigil_rt::Result;\n\n");

    for schema in &program.schemas {
        out.push_str(&emit_schema(schema));
        out.push('\n');
    }

    for process in &program.processes {
        out.push_str(&emit_process(process));
        out.push('\n');
    }

    let primary_ty = primary_message_type(program);
    let (_env, transform_types) = crate::analysis::types::infer_program(program);
    let externals = collect_externals(program);
    if !externals.is_empty() {
        out.push_str("// External transforms — residual risk (bodies are stubs).\n");
        out.push_str("// Types are propagated from schemas and field usage.\n");
        for name in &externals {
            let (in_ty, out_ty) = transform_types
                .get(name)
                .cloned()
                .unwrap_or_else(|| (primary_ty.clone(), primary_ty.clone()));
            out.push_str(&emit_external_stub(name, &in_ty, &out_ty));
            out.push('\n');
        }
    }

    out.push_str(&emit_smoke_test(program));
    out
}

fn primary_message_type(program: &Program) -> String {
    program
        .processes
        .first()
        .and_then(|p| p.handlers.first())
        .map(|h| rust_type(&h.msg_ty))
        .unwrap_or_else(|| "()".into())
}

fn emit_schema(schema: &Schema) -> String {
    let mut s = String::new();
    s.push_str("#[derive(Clone, Debug, Default)]\n");
    s.push_str(&format!("pub struct {} {{\n", schema.name));
    for (fname, fty) in &schema.fields {
        s.push_str(&format!("    pub {}: {},\n", fname, rust_type(fty)));
    }
    s.push_str("}\n");
    s
}

fn emit_process(process: &Process) -> String {
    let states: Vec<String> = process.states.iter().map(|s| s.name.clone()).collect();
    let mut s = String::new();

    s.push_str(&format!("pub struct {} {{\n", process.name));
    for st in &process.states {
        // Public so integration tests / callers can observe local state.
        s.push_str(&format!("    pub {}: {},\n", st.name, rust_type(&st.ty)));
    }
    s.push_str("}\n\n");

    s.push_str(&format!("impl {} {{\n", process.name));
    s.push_str("    pub fn new() -> Self {\n        Self {\n");
    for st in &process.states {
        s.push_str(&format!(
            "            {}: {},\n",
            st.name,
            emit_expr(&st.init, &[], "")
        ));
    }
    s.push_str("        }\n    }\n\n");

    for handler in &process.handlers {
        s.push_str(&emit_handler(handler, &states));
        s.push('\n');
    }
    s.push_str("}\n");
    s
}

fn emit_handler(handler: &OnHandler, states: &[String]) -> String {
    let msg_ty = rust_type(&handler.msg_ty);
    let method = format!("on_{}", handler.msg_name);
    let mut s = String::new();
    s.push_str(&format!(
        "    pub async fn {method}(&mut self, {}: {msg_ty}) -> Result<()> {{\n",
        handler.msg_name
    ));

    for stmt in &handler.body {
        s.push_str(&emit_stmt(stmt, "        ", states, &handler.msg_name));
    }

    s.push_str("        Ok(())\n");
    s.push_str("    }\n");
    s
}

fn emit_stmt(stmt: &Stmt, indent: &str, states: &[String], msg: &str) -> String {
    match stmt {
        Stmt::Let { name, expr, .. } => {
            // Prefer multi-line for timeout pipelines so the recover path is readable.
            if is_timed_pipeline(expr) {
                format!(
                    "{indent}let {name} = {};\n",
                    emit_expr_multiline(expr, states, msg, indent)
                )
            } else {
                format!("{indent}let {name} = {};\n", emit_expr(expr, states, msg))
            }
        }
        Stmt::Assign { name, expr, .. } => {
            format!(
                "{indent}self.{name} = {};\n",
                emit_expr(expr, states, msg)
            )
        }
        Stmt::Expr { expr, .. } => {
            format!("{indent}let _ = {};\n", emit_expr(expr, states, msg))
        }
    }
}

fn is_timed_pipeline(expr: &Expr) -> bool {
    match expr {
        Expr::Pipeline { steps, .. } => steps.iter().any(|s| {
            s.tags
                .iter()
                .any(|t| matches!(t, Tag::Timeout { .. }))
        }),
        _ => false,
    }
}

fn emit_expr(expr: &Expr, states: &[String], msg: &str) -> String {
    match expr {
        Expr::Ident { name, .. } => {
            if states.iter().any(|s| s == name) {
                format!("self.{name}")
            } else {
                name.clone()
            }
        }
        Expr::FieldAccess { base, field, .. } => {
            if states.iter().any(|s| s == base) {
                format!("self.{base}.{field}")
            } else {
                format!("{base}.{field}")
            }
        }
        Expr::Literal { value, .. } => emit_literal(value),
        Expr::Call { name, args, .. } => {
            let a = args
                .iter()
                .map(|e| emit_expr(e, states, msg))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{name}({a})?")
        }
        Expr::Binary { op, lhs, rhs, .. } => {
            let op_s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
            };
            format!(
                "({} {} {})",
                emit_expr(lhs, states, msg),
                op_s,
                emit_expr(rhs, states, msg)
            )
        }
        Expr::Pipeline { base, steps, .. } => emit_pipeline(base, steps, states, msg, false, ""),
    }
}

fn emit_expr_multiline(expr: &Expr, states: &[String], msg: &str, indent: &str) -> String {
    match expr {
        Expr::Pipeline { base, steps, .. } => {
            emit_pipeline(base, steps, states, msg, true, indent)
        }
        other => emit_expr(other, states, msg),
    }
}

fn emit_pipeline(
    base: &Expr,
    steps: &[crate::frontend::ast::PipeStep],
    states: &[String],
    msg: &str,
    multiline: bool,
    indent: &str,
) -> String {
    let mut current = emit_expr(base, states, msg);
    for step in steps {
        let transform = match &step.expr {
            Expr::Ident { name, .. } => name.clone(),
            Expr::Call { name, .. } => name.clone(),
            other => emit_expr(other, states, msg),
        };

        let timeout_ms = step.tags.iter().find_map(|t| match t {
            Tag::Timeout { expr, .. } => match expr {
                Expr::Literal {
                    value: Literal::DurationMs(ms),
                    ..
                } => Some(*ms),
                _ => None,
            },
            _ => None,
        });
        let recover = step.tags.iter().find_map(|t| match t {
            Tag::Recover { with, .. } => match with {
                Expr::Ident { name, .. } => Some(name.clone()),
                Expr::Call { name, .. } => Some(name.clone()),
                _ => None,
            },
            _ => None,
        });

        if let Some(ms) = timeout_ms {
            let fallback = recover.unwrap_or_else(|| transform.clone());
            if multiline {
                let inner = format!(
                    "match timeout(Duration::from_millis({ms}), async {{ {transform}({current}.clone()) }}).await {{\n\
{indent}    Ok(Ok(v)) => v,\n\
{indent}    Ok(Err(_)) | Err(_) => {fallback}({current})?,\n\
{indent}}}"
                );
                current = inner;
            } else {
                current = format!(
                    "(match timeout(Duration::from_millis({ms}), async {{ {transform}({current}.clone()) }}).await {{ Ok(Ok(v)) => v, Ok(Err(_)) | Err(_) => {fallback}({current})?, }})"
                );
            }
        } else {
            current = format!("{transform}({current})?");
        }
    }
    current
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Int(i) => i.to_string(),
        Literal::Float(f) => {
            let s = format!("{f}");
            if s.contains('.') {
                s
            } else {
                format!("{s}.0")
            }
        }
        Literal::String(s) => format!("\"{s}\".to_string()"),
        Literal::Bool(b) => b.to_string(),
        Literal::DurationMs(ms) => format!("Duration::from_millis({ms})"),
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Int => "i64".into(),
        Type::Float => "f64".into(),
        Type::String => "String".into(),
        Type::Bool => "bool".into(),
        Type::UUID => "String".into(),
        Type::Bytes => "Vec<u8>".into(),
        Type::Duration => "Duration".into(),
        Type::Named(n) => n.clone(),
    }
}

fn emit_external_stub(name: &str, in_ty: &str, out_ty: &str) -> String {
    if in_ty == out_ty {
        format!(
            "fn {name}(input: {in_ty}) -> Result<{out_ty}> {{\n    Ok(input)\n}}\n"
        )
    } else {
        // Stage changes schema: build a default output (residual: real logic belongs here).
        format!(
            "fn {name}(_input: {in_ty}) -> Result<{out_ty}> {{\n    Ok({out_ty}::default())\n}}\n"
        )
    }
}

fn collect_externals(program: &Program) -> BTreeSet<String> {
    let mut set = BTreeSet::new();
    for process in &program.processes {
        let mut locals: BTreeSet<String> =
            process.states.iter().map(|s| s.name.clone()).collect();
        for handler in &process.handlers {
            locals.insert(handler.msg_name.clone());
            for stmt in &handler.body {
                match stmt {
                    Stmt::Let { name, expr, .. } => {
                        walk_externals(expr, &mut set);
                        locals.insert(name.clone());
                    }
                    Stmt::Assign { expr, .. } | Stmt::Expr { expr, .. } => {
                        walk_externals(expr, &mut set);
                    }
                }
            }
        }
    }
    set
}

fn walk_externals(expr: &Expr, set: &mut BTreeSet<String>) {
    match expr {
        Expr::Call { name, args, .. } => {
            set.insert(name.clone());
            for a in args {
                walk_externals(a, set);
            }
        }
        Expr::Pipeline { base, steps, .. } => {
            walk_externals(base, set);
            for step in steps {
                match &step.expr {
                    Expr::Ident { name, .. } | Expr::Call { name, .. } => {
                        set.insert(name.clone());
                    }
                    other => walk_externals(other, set),
                }
                for tag in &step.tags {
                    if let Tag::Recover { with, .. } = tag {
                        if let Expr::Ident { name, .. } = with {
                            set.insert(name.clone());
                        }
                    }
                }
            }
        }
        Expr::Binary { lhs, rhs, .. } => {
            walk_externals(lhs, set);
            walk_externals(rhs, set);
        }
        Expr::Ident { .. } | Expr::FieldAccess { .. } | Expr::Literal { .. } => {}
    }
}

fn emit_smoke_test(program: &Program) -> String {
    if program.processes.is_empty() {
        return String::new();
    }
    let process = &program.processes[0];
    let mut s = String::new();
    s.push_str("#[cfg(test)]\nmod tests {\n    use super::*;\n\n");
    s.push_str("    #[tokio::test]\n");
    s.push_str("    async fn smoke() {\n");
    s.push_str(&format!("        let mut p = {}::new();\n", process.name));
    if let Some(handler) = process.handlers.first() {
        let ty = rust_type(&handler.msg_ty);
        s.push_str(&format!("        let msg = {ty}::default();\n"));
        s.push_str(&format!(
            "        p.on_{}(msg).await.expect(\"handler should succeed\");\n",
            handler.msg_name
        ));
        // Observe local state was reachable (does not assert business values).
        for st in &process.states {
            s.push_str(&format!("        let _ = &p.{};\n", st.name));
        }
    }
    s.push_str("    }\n}\n");
    s
}

pub fn emit_cargo_toml(package_name: &str, sigil_rt_path: &str) -> String {
    format!(
        r#"[package]
name = "{package_name}"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {{ version = "1", features = ["time", "macros", "rt-multi-thread"] }}
sigil_rt = {{ path = "{sigil_rt_path}" }}
thiserror = "1"

[lib]
path = "src/lib.rs"
"#
    )
}

/// Compute a relative path from `out_dir` to the workspace `sigil_rt` crate.
pub fn relative_sigil_rt_path(out_dir: &std::path::Path) -> String {
    for rel in ["../sigil_rt", "../../sigil_rt", "../../../sigil_rt"] {
        if out_dir.join(rel).exists() {
            return rel.to_string();
        }
    }
    // Default: nested generated/<name> under the workspace root
    if out_dir.file_name().and_then(|s| s.to_str()) == Some("generated") {
        "../sigil_rt".into()
    } else {
        "../../sigil_rt".into()
    }
}
