//! Backend: Program + Graph IR → ownership-safe Rust crate.
//! Level-1 guarantees are preserved by construction in the emitted code.

use crate::analysis::ir::GraphIR;
use crate::frontend::ast::{
    BinOp, Expr, Literal, OnHandler, Process, Program, Schema, Stmt, Tag, Type,
};
use std::collections::BTreeSet;

/// Emit a full Rust library source from the checked program and its Graph IR.
pub fn emit(program: &Program, ir: &GraphIR) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by sigilc — do not edit by hand\n");
    out.push_str("//\n");
    out.push_str(&format!("// Process: {}\n", ir.process_name));
    out.push_str(&format!(
        "// Local state: {}\n",
        if ir.local_states.is_empty() {
            "(none)".into()
        } else {
            ir.local_states.join(", ")
        }
    ));
    let timeouts: Vec<_> = ir
        .nodes
        .iter()
        .filter_map(|n| match n {
            crate::analysis::ir::Node::Timeout { ms, .. } => Some(format!("{ms}ms")),
            _ => None,
        })
        .collect();
    if !timeouts.is_empty() {
        out.push_str(&format!("// Timed stages: {}\n", timeouts.join(", ")));
    }
    out.push_str("//\n");
    out.push_str("// Level-1 guarantees preserved by construction:\n");
    out.push_str("//   - process-local state only (no shared mutability)\n");
    out.push_str("//   - no null values\n");
    out.push_str("//   - every @timeout has an explicit @recover path\n\n");

    out.push_str("use std::time::Duration;\n");
    out.push_str("use tokio::time::timeout;\n");
    out.push_str("use sigil_rt::Result;\n\n");

    for schema in &program.schemas {
        out.push_str(&emit_schema(schema));
        out.push('\n');
    }

    for process in &program.processes {
        out.push_str(&emit_process(process));
        out.push('\n');
        out.push_str(&emit_actor(process));
        out.push('\n');
    }

    let primary_ty = primary_message_type(program);
    let (_env, transform_types) = crate::analysis::types::infer_program(program);

    // Prefer declared transforms: pure bodies compile; empty bodies are residual stubs.
    let mut emitted: BTreeSet<String> = BTreeSet::new();
    if !program.transforms.is_empty() {
        out.push_str("// --- declared transforms ---\n");
        for t in &program.transforms {
            out.push_str(&emit_declared_transform(t));
            out.push('\n');
            emitted.insert(t.name.clone());
        }
    }

    let externals = collect_externals(program);
    let leftover: Vec<_> = externals.difference(&emitted).cloned().collect();
    if !leftover.is_empty() {
        out.push_str("// --- undeclared transforms (residual stubs) ---\n");
        for name in leftover {
            let (in_ty, out_ty) = transform_types
                .get(&name)
                .cloned()
                .unwrap_or_else(|| (primary_ty.clone(), primary_ty.clone()));
            out.push_str(&emit_external_stub(&name, &in_ty, &out_ty));
            out.push('\n');
        }
    }

    out.push_str(&emit_smoke_test(program));
    out
}

fn emit_declared_transform(t: &crate::frontend::ast::TransformDecl) -> String {
    let in_ty = rust_type(&t.param_ty);
    let out_ty = rust_type(&t.return_ty);
    let param = &t.param;
    if t.body.is_empty() {
        return emit_external_stub(&t.name, &in_ty, &out_ty);
    }
    let mut body_src = String::new();
    for stmt in &t.body {
        match stmt {
            Stmt::Let { name, expr, .. } => {
                body_src.push_str(&format!(
                    "    let {name} = {};\n",
                    emit_expr(expr, &[], param)
                ));
            }
            Stmt::Expr { expr, .. } => {
                body_src.push_str(&format!(
                    "    return Ok({});\n",
                    emit_expr(expr, &[], param)
                ));
            }
            Stmt::Assign { .. } => {
                body_src.push_str("    /* unsupported assign in transform */\n");
            }
        }
    }
    if !body_src.contains("return Ok") {
        body_src.push_str(&format!("    Ok({param})\n"));
    }
    format!(
        "fn {}({param}: {in_ty}) -> Result<{out_ty}> {{\n{body_src}}}\n",
        t.name
    )
}

fn primary_message_type(program: &Program) -> String {
    program
        .processes
        .first()
        .and_then(|p| p.handlers.first())
        .map(|h| rust_type(&h.msg_ty))
        .unwrap_or_else(|| "()".into())
}

fn emit_schema(schema: &Schema) -> String {
    let mut s = String::new();
    s.push_str("#[derive(Clone, Debug, Default)]\n");
    s.push_str(&format!("pub struct {} {{\n", schema.name));
    for (fname, fty) in &schema.fields {
        s.push_str(&format!("    pub {}: {},\n", fname, rust_type(fty)));
    }
    s.push_str("}\n");
    s
}

fn emit_process(process: &Process) -> String {
    let states: Vec<String> = process.states.iter().map(|s| s.name.clone()).collect();
    let mut s = String::new();

    s.push_str(&format!("pub struct {} {{\n", process.name));
    for st in &process.states {
        // Public so integration tests / callers can observe local state.
        s.push_str(&format!("    pub {}: {},\n", st.name, rust_type(&st.ty)));
    }
    s.push_str("}\n\n");

    s.push_str(&format!("impl {} {{\n", process.name));
    s.push_str("    pub fn new() -> Self {\n        Self {\n");
    for st in &process.states {
        s.push_str(&format!(
            "            {}: {},\n",
            st.name,
            emit_expr(&st.init, &[], "")
        ));
    }
    s.push_str("        }\n    }\n\n");

    for handler in &process.handlers {
        s.push_str(&emit_handler(handler, &states));
        s.push('\n');
    }
    s.push_str("}\n");
    s
}


/// Emit shared-nothing actor machinery for a process.
///
/// This is where the Level-1 "no shared mutable state" guarantee is realized
/// in the generated Rust, not just checked by the compiler:
///   - `spawn(self)` MOVES the state into an isolated tokio task; after that
///     no reference to it can exist anywhere else in the program.
///   - The only way in is a message via a Clone-able `Handle` (an mpsc Sender).
///   - The only way out is `join()` after the channel closes.
/// There is no `Arc`, no `Mutex`, and no way to observe state concurrently.
fn emit_actor(process: &Process) -> String {
    if process.handlers.is_empty() {
        return String::new();
    }
    let p = &process.name;
    let mut s = String::new();

    if process.handlers.len() == 1 {
        let h = &process.handlers[0];
        let msg_ty = rust_type(&h.msg_ty);
        let method = format!("on_{}", h.msg_name);
        s.push_str(&format!(
            "/// Clone-able, thread-safe handle to a running `{p}` actor.\n\
             /// Sending is the ONLY way to interact with the actor's state.\n\
             #[derive(Clone)]\n\
             pub struct {p}Handle {{\n\
             \x20   tx: tokio::sync::mpsc::Sender<{msg_ty}>,\n\
             }}\n\n\
             impl {p}Handle {{\n\
             \x20   pub async fn send(&self, msg: {msg_ty}) -> Result<()> {{\n\
             \x20       self.tx\n\
             \x20           .send(msg)\n\
             \x20           .await\n\
             \x20           .map_err(|_| sigil_rt::SigilError::Transform(\"actor stopped\".into()))\n\
             \x20   }}\n\
             }}\n\n\
             impl {p} {{\n\
             \x20   /// Move this process's state into an isolated task.\n\
             \x20   /// After `spawn`, the state is unreachable except via messages;\n\
             \x20   /// it is returned intact when the last Handle is dropped.\n\
             \x20   pub fn spawn(mut self, capacity: usize) -> ({p}Handle, tokio::task::JoinHandle<Self>) {{\n\
             \x20       let (tx, mut rx) = tokio::sync::mpsc::channel::<{msg_ty}>(capacity);\n\
             \x20       let join = tokio::spawn(async move {{\n\
             \x20           while let Some(msg) = rx.recv().await {{\n\
             \x20               if let Err(e) = self.{method}(msg).await {{\n\
             \x20                   eprintln!(\"[{p}] handler error (recovered stages already applied): {{e:?}}\");\n\
             \x20               }}\n\
             \x20           }}\n\
             \x20           self\n\
             \x20       }});\n\
             \x20       ({p}Handle {{ tx }}, join)\n\
             \x20   }}\n\
             }}\n"
        ));
        return s;
    }

    // Multiple handlers: dispatch enum, one variant per message type.
    let enum_name = format!("{p}Msg");
    s.push_str(&format!("pub enum {enum_name} {{\n"));
    for h in &process.handlers {
        s.push_str(&format!(
            "    {}({}),\n",
            variant_name(&h.msg_name),
            rust_type(&h.msg_ty)
        ));
    }
    s.push_str("}\n\n");

    s.push_str(&format!(
        "#[derive(Clone)]\npub struct {p}Handle {{\n    tx: tokio::sync::mpsc::Sender<{enum_name}>,\n}}\n\nimpl {p}Handle {{\n"
    ));
    for h in &process.handlers {
        s.push_str(&format!(
            "    pub async fn send_{}(&self, msg: {}) -> Result<()> {{\n        self.tx.send({enum_name}::{}(msg)).await.map_err(|_| sigil_rt::SigilError::Transform(\"actor stopped\".into()))\n    }}\n",
            h.msg_name,
            rust_type(&h.msg_ty),
            variant_name(&h.msg_name)
        ));
    }
    s.push_str("}\n\n");

    s.push_str(&format!(
        "impl {p} {{\n    pub fn spawn(mut self, capacity: usize) -> ({p}Handle, tokio::task::JoinHandle<Self>) {{\n        let (tx, mut rx) = tokio::sync::mpsc::channel::<{enum_name}>(capacity);\n        let join = tokio::spawn(async move {{\n            while let Some(msg) = rx.recv().await {{\n                let r = match msg {{\n"
    ));
    for h in &process.handlers {
        s.push_str(&format!(
            "                    {enum_name}::{}(m) => self.on_{}(m).await,\n",
            variant_name(&h.msg_name),
            h.msg_name
        ));
    }
    s.push_str(&format!(
        "                }};\n                if let Err(e) = r {{\n                    eprintln!(\"[{p}] handler error: {{e:?}}\");\n                }}\n            }}\n            self\n        }});\n        ({p}Handle {{ tx }}, join)\n    }}\n}}\n"
    ));
    s
}

fn variant_name(msg_name: &str) -> String {
    let mut c = msg_name.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

fn emit_handler(handler: &OnHandler, states: &[String]) -> String {
    let msg_ty = rust_type(&handler.msg_ty);
    let method = format!("on_{}", handler.msg_name);
    let mut s = String::new();
    s.push_str(&format!(
        "    pub async fn {method}(&mut self, {}: {msg_ty}) -> Result<()> {{\n",
        handler.msg_name
    ));

    for stmt in &handler.body {
        s.push_str(&emit_stmt(stmt, "        ", states, &handler.msg_name));
    }

    s.push_str("        Ok(())\n");
    s.push_str("    }\n");
    s
}

fn emit_stmt(stmt: &Stmt, indent: &str, states: &[String], msg: &str) -> String {
    match stmt {
        Stmt::Let { name, expr, .. } => {
            // Prefer multi-line for timeout pipelines so the recover path is readable.
            if is_timed_pipeline(expr) {
                format!(
                    "{indent}let {name} = {};\n",
                    emit_expr_multiline(expr, states, msg, indent)
                )
            } else {
                format!("{indent}let {name} = {};\n", emit_expr(expr, states, msg))
            }
        }
        Stmt::Assign { name, expr, .. } => {
            format!(
                "{indent}self.{name} = {};\n",
                emit_expr(expr, states, msg)
            )
        }
        Stmt::Expr { expr, .. } => {
            format!("{indent}let _ = {};\n", emit_expr(expr, states, msg))
        }
    }
}

fn is_timed_pipeline(expr: &Expr) -> bool {
    match expr {
        Expr::Pipeline { steps, .. } => steps.iter().any(|s| {
            s.tags
                .iter()
                .any(|t| matches!(t, Tag::Timeout { .. }))
        }),
        _ => false,
    }
}

fn emit_expr(expr: &Expr, states: &[String], msg: &str) -> String {
    match expr {
        Expr::Ident { name, .. } => {
            if states.iter().any(|s| s == name) {
                format!("self.{name}")
            } else {
                name.clone()
            }
        }
        Expr::FieldAccess { base, field, .. } => {
            if states.iter().any(|s| s == base) {
                format!("self.{base}.{field}")
            } else {
                format!("{base}.{field}")
            }
        }
        Expr::Literal { value, .. } => emit_literal(value),
        Expr::Call { name, args, .. } => {
            let a = args
                .iter()
                .map(|e| emit_expr(e, states, msg))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{name}({a})?")
        }
        Expr::Binary { op, lhs, rhs, .. } => {
            let op_s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Le => "<=",
                BinOp::Ge => ">=",
                BinOp::Lt => "<",
                BinOp::Gt => ">",
                BinOp::Eq => "==",
            };
            format!(
                "({} {} {})",
                emit_expr(lhs, states, msg),
                op_s,
                emit_expr(rhs, states, msg)
            )
        }
        Expr::Pipeline { base, steps, .. } => emit_pipeline(base, steps, states, msg, false, ""),
    }
}

fn emit_expr_multiline(expr: &Expr, states: &[String], msg: &str, indent: &str) -> String {
    match expr {
        Expr::Pipeline { base, steps, .. } => {
            emit_pipeline(base, steps, states, msg, true, indent)
        }
        other => emit_expr(other, states, msg),
    }
}

fn emit_pipeline(
    base: &Expr,
    steps: &[crate::frontend::ast::PipeStep],
    states: &[String],
    msg: &str,
    multiline: bool,
    indent: &str,
) -> String {
    let mut current = emit_expr(base, states, msg);
    for step in steps {
        let transform = match &step.expr {
            Expr::Ident { name, .. } => name.clone(),
            Expr::Call { name, .. } => name.clone(),
            other => emit_expr(other, states, msg),
        };

        let timeout_ms = step.tags.iter().find_map(|t| match t {
            Tag::Timeout { expr, .. } => match expr {
                Expr::Literal {
                    value: Literal::DurationMs(ms),
                    ..
                } => Some(*ms),
                _ => None,
            },
            _ => None,
        });
        let recover = step.tags.iter().find_map(|t| match t {
            Tag::Recover { with, .. } => match with {
                Expr::Ident { name, .. } => Some(name.clone()),
                Expr::Call { name, .. } => Some(name.clone()),
                _ => None,
            },
            _ => None,
        });

        if let Some(ms) = timeout_ms {
            let fallback = recover.unwrap_or_else(|| transform.clone());
            if multiline {
                let inner = format!(
                    "match timeout(Duration::from_millis({ms}), async {{ {transform}({current}.clone()) }}).await {{\n\
{indent}    Ok(Ok(v)) => v,\n\
{indent}    Ok(Err(_)) | Err(_) => {fallback}({current})?,\n\
{indent}}}"
                );
                current = inner;
            } else {
                current = format!(
                    "(match timeout(Duration::from_millis({ms}), async {{ {transform}({current}.clone()) }}).await {{ Ok(Ok(v)) => v, Ok(Err(_)) | Err(_) => {fallback}({current})?, }})"
                );
            }
        } else {
            current = format!("{transform}({current})?");
        }
    }
    current
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Int(i) => i.to_string(),
        Literal::Float(f) => {
            let s = format!("{f}");
            if s.contains('.') {
                s
            } else {
                format!("{s}.0")
            }
        }
        Literal::String(s) => format!("\"{s}\".to_string()"),
        Literal::Bool(b) => b.to_string(),
        Literal::DurationMs(ms) => format!("Duration::from_millis({ms})"),
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Int => "i64".into(),
        Type::Float => "f64".into(),
        Type::String => "String".into(),
        Type::Bool => "bool".into(),
        Type::UUID => "String".into(),
        Type::Bytes => "Vec<u8>".into(),
        Type::Duration => "Duration".into(),
        Type::Named(n) => n.clone(),
    }
}

fn emit_external_stub(name: &str, in_ty: &str, out_ty: &str) -> String {
    if in_ty == out_ty {
        format!(
            "fn {name}(input: {in_ty}) -> Result<{out_ty}> {{\n    Ok(input)\n}}\n"
        )
    } else {
        // Stage changes schema: build a default output (residual: real logic belongs here).
        format!(
            "fn {name}(_input: {in_ty}) -> Result<{out_ty}> {{\n    Ok({out_ty}::default())\n}}\n"
        )
    }
}

fn collect_externals(program: &Program) -> BTreeSet<String> {
    let mut set = BTreeSet::new();
    for process in &program.processes {
        let mut locals: BTreeSet<String> =
            process.states.iter().map(|s| s.name.clone()).collect();
        for handler in &process.handlers {
            locals.insert(handler.msg_name.clone());
            for stmt in &handler.body {
                match stmt {
                    Stmt::Let { name, expr, .. } => {
                        walk_externals(expr, &mut set);
                        locals.insert(name.clone());
                    }
                    Stmt::Assign { expr, .. } | Stmt::Expr { expr, .. } => {
                        walk_externals(expr, &mut set);
                    }
                }
            }
        }
    }
    set
}

fn walk_externals(expr: &Expr, set: &mut BTreeSet<String>) {
    match expr {
        Expr::Call { name, args, .. } => {
            set.insert(name.clone());
            for a in args {
                walk_externals(a, set);
            }
        }
        Expr::Pipeline { base, steps, .. } => {
            walk_externals(base, set);
            for step in steps {
                match &step.expr {
                    Expr::Ident { name, .. } | Expr::Call { name, .. } => {
                        set.insert(name.clone());
                    }
                    other => walk_externals(other, set),
                }
                for tag in &step.tags {
                    if let Tag::Recover { with, .. } = tag {
                        if let Expr::Ident { name, .. } = with {
                            set.insert(name.clone());
                        }
                    }
                }
            }
        }
        Expr::Binary { lhs, rhs, .. } => {
            walk_externals(lhs, set);
            walk_externals(rhs, set);
        }
        Expr::Ident { .. } | Expr::FieldAccess { .. } | Expr::Literal { .. } => {}
    }
}

fn emit_smoke_test(program: &Program) -> String {
    if program.processes.is_empty() {
        return String::new();
    }
    let process = &program.processes[0];
    let mut s = String::new();
    s.push_str("#[cfg(test)]\nmod tests {\n    use super::*;\n\n");
    s.push_str("    #[tokio::test]\n");
    s.push_str("    async fn smoke() {\n");
    s.push_str(&format!("        let mut p = {}::new();\n", process.name));
    if let Some(handler) = process.handlers.first() {
        let ty = rust_type(&handler.msg_ty);
        s.push_str(&format!("        let msg = {ty}::default();\n"));
        s.push_str(&format!(
            "        p.on_{}(msg).await.expect(\"handler should succeed\");\n",
            handler.msg_name
        ));
        // Observe local state was reachable (does not assert business values).
        for st in &process.states {
            s.push_str(&format!("        let _ = &p.{};\n", st.name));
        }
    }
    s.push_str("    }\n}\n");
    s
}

pub fn emit_cargo_toml(package_name: &str, sigil_rt_path: &str, with_main: bool) -> String {
    let bin_section = if with_main {
        "\n[[bin]]\nname = \"demo\"\npath = \"src/main.rs\"\n"
    } else {
        ""
    };
    format!(
        "[workspace]\n\n[package]\nname = \"{package_name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\ntokio = {{ version = \"1\", features = [\"time\", \"macros\", \"rt-multi-thread\", \"sync\"] }}\nsigil_rt = {{ path = \"{sigil_rt_path}\" }}\nthiserror = \"1\"\n\n[lib]\nname = \"sigil_gen\"\npath = \"src/lib.rs\"\n{bin_section}"
    )
}

/// Emit a runnable main that stress-tests the process as a fleet of
/// shared-nothing actors: SHARDS isolated instances, PRODUCERS concurrent
/// tasks on a multi-threaded runtime, deterministic aggregate at the end.
/// No locks appear anywhere in the generated program.
pub fn emit_demo_main(program: &Program) -> String {
    if program.processes.is_empty() {
        return "fn main() {\n    println!(\"no process\");\n}\n".into();
    }
    let process = &program.processes[0];
    let p = &process.name;
    let Some(handler) = process.handlers.first() else {
        return "fn main() {\n    println!(\"no handler\");\n}\n".into();
    };
    let msg_ty = rust_type(&handler.msg_ty);

    // Synthesize per-message field values so aggregates are checkable:
    // Int fields = 1, Float fields = 1.0, Strings get unique ids.
    let mut field_init = String::new();
    if let Type::Named(name) = &handler.msg_ty {
        if let Some(schema) = program.schemas.iter().find(|sc| sc.name == *name) {
            for (fname, fty) in &schema.fields {
                match fty {
                    Type::Int => field_init.push_str(&format!(
                        "                msg.{fname} = 1;\n"
                    )),
                    Type::Float => field_init.push_str(&format!(
                        "                msg.{fname} = 1.0;\n"
                    )),
                    Type::String => field_init.push_str(&format!(
                        "                msg.{fname} = format!(\"m-{{prod}}-{{i}}\");\n"
                    )),
                    Type::Bool => field_init.push_str(&format!(
                        "                msg.{fname} = true;\n"
                    )),
                    _ => {}
                }
            }
        }
    }

    // Aggregate numeric states across shards.
    let mut agg_decl = String::new();
    let mut agg_add = String::new();
    let mut agg_print = String::new();
    let mut shard_print_fmt = String::new();
    let mut shard_print_args = String::new();
    for st in &process.states {
        match st.ty {
            Type::Int => {
                agg_decl.push_str(&format!("    let mut agg_{}: i64 = 0;\n", st.name));
                agg_add.push_str(&format!("        agg_{} += st.{};\n", st.name, st.name));
                agg_print.push_str(&format!(
                    "    println!(\"aggregate {} = {{}}\", agg_{});\n",
                    st.name, st.name
                ));
                shard_print_fmt.push_str(&format!(" {}={{}}", st.name));
                shard_print_args.push_str(&format!(", st.{}", st.name));
            }
            Type::Float => {
                agg_decl.push_str(&format!("    let mut agg_{}: f64 = 0.0;\n", st.name));
                agg_add.push_str(&format!("        agg_{} += st.{};\n", st.name, st.name));
                agg_print.push_str(&format!(
                    "    println!(\"aggregate {} = {{:.1}}\", agg_{});\n",
                    st.name, st.name
                ));
                shard_print_fmt.push_str(&format!(" {}={{:.1}}", st.name));
                shard_print_args.push_str(&format!(", st.{}", st.name));
            }
            _ => {
                shard_print_fmt.push_str(&format!(" {}={{:?}}", st.name));
                shard_print_args.push_str(&format!(", st.{}", st.name));
            }
        }
    }

    let lib_name = "{{LIB}}"; // patched by caller via crate name? No: use crate path.
    let _ = lib_name;

    format!(
        r#"// AUTO-GENERATED by sigilc — concurrent demo binary
//
// {shards} isolated `{p}` actors, {producers} producer tasks, {msgs} messages
// on a multi-threaded runtime. Every counter below is exact — there is no
// lock, no Arc, and no atomic in this program. State isolation is by
// construction: each actor owns its state inside its own task.

use sigil_gen::*;
use std::time::Instant;

#[tokio::main(flavor = "multi_thread")]
async fn main() {{
    const SHARDS: usize = {shards};
    const PRODUCERS: usize = {producers};
    const MSGS_PER_PRODUCER: usize = {per_producer};
    const TOTAL: usize = PRODUCERS * MSGS_PER_PRODUCER;

    let mut handles = Vec::new();
    let mut joins = Vec::new();
    for _ in 0..SHARDS {{
        let (h, j) = {p}::new().spawn(1024);
        handles.push(h);
        joins.push(j);
    }}

    let t0 = Instant::now();
    let mut producers = Vec::new();
    for prod in 0..PRODUCERS {{
        let hs = handles.clone();
        producers.push(tokio::spawn(async move {{
            for i in 0..MSGS_PER_PRODUCER {{
                let mut msg = {msg_ty}::default();
{field_init}                let shard = (prod + i) % hs.len();
                if hs[shard].send(msg).await.is_err() {{
                    break;
                }}
            }}
        }}));
    }}
    for t in producers {{
        let _ = t.await;
    }}
    drop(handles); // close all channels → actors drain and return their state

    println!("=== {p} concurrent demo ===");
    println!(
        "{{}} shards x {{}} producers, {{}} messages, {{}} worker threads",
        SHARDS,
        PRODUCERS,
        TOTAL,
        std::thread::available_parallelism().map(|n| n.get()).unwrap_or(1)
    );
{agg_decl}    for (idx, j) in joins.into_iter().enumerate() {{
        let st = j.await.expect("actor task panicked");
        println!("shard {{idx}}:{shard_print_fmt}"{shard_print_args});
{agg_add}    }}
{agg_print}    println!("expected messages   = {{TOTAL}}");
    println!("elapsed = {{:?}} (locks used: 0)", t0.elapsed());
}}
"#,
        shards = 8,
        producers = 64,
        per_producer = 250,
        msgs = 64 * 250,
    )
}

/// Compute a relative path from `out_dir` to the workspace `sigil_rt` crate.
pub fn relative_sigil_rt_path(out_dir: &std::path::Path) -> String {
    for rel in ["../sigil_rt", "../../sigil_rt", "../../../sigil_rt"] {
        if out_dir.join(rel).exists() {
            return rel.to_string();
        }
    }
    if out_dir.file_name().and_then(|s| s.to_str()) == Some("generated") {
        "../sigil_rt".into()
    } else {
        "../../sigil_rt".into()
    }
}
